# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crusher < Formula
  desc "crusher is a utility bigtable applications"
  homepage "https://github.com/JamesWoolfenden/crusher#readme"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JamesWoolfenden/crusher/releases/download/v0.0.4/crusher_0.0.4_darwin_arm64.tar.gz"
      sha256 "7dcb2bb9970ba0a965d8a03321e2290c3fc6fdc190c996180e9bd4db71738824"

      def install
        bin.install "crusher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/crusher/releases/download/v0.0.4/crusher_0.0.4_darwin_amd64.tar.gz"
      sha256 "b8bc872ecd08158ec89c303a7ebc696262b3dd97c7d4cf3b6352538ade2f4344"

      def install
        bin.install "crusher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/crusher/releases/download/v0.0.4/crusher_0.0.4_linux_amd64.tar.gz"
      sha256 "35c076a326ed04c14ecf6fd88d2b7302c312b3cada98bd465fd69dcaf65420de"

      def install
        bin.install "crusher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/crusher/releases/download/v0.0.4/crusher_0.0.4_linux_arm64.tar.gz"
      sha256 "3a18e45010de712dc0a216e95ab44be4437199fc43d6119ce20489fd5ac38952"

      def install
        bin.install "crusher"
      end
    end
  end

  test do
    system "#{bin}/crusher", "--help"
  end
end
