# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghat < Formula
  desc "Ghat is a tool for updating GHA dependencies"
  homepage "https://github.com/JamesWoolfenden/ghat#readme"
  version "0.0.26"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v0.0.26/ghat_0.0.26_darwin_arm64.tar.gz"
      sha256 "183725ba89795dd3e0c1e5a3576b3313db5ce18c5870cb1b57000e68f570562e"

      def install
        bin.install "ghat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v0.0.26/ghat_0.0.26_darwin_amd64.tar.gz"
      sha256 "2b2f3d45bac2d1380e9c3fd7a3cd7d709f35c9d952e0f3eebecf5595b2960461"

      def install
        bin.install "ghat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v0.0.26/ghat_0.0.26_linux_amd64.tar.gz"
      sha256 "c8d2d8c808402d42f96d3796f30871daedd547497e188151eda80e9ba096c533"

      def install
        bin.install "ghat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v0.0.26/ghat_0.0.26_linux_arm64.tar.gz"
      sha256 "91ecbda91d21fe0aeae136a7311972c40564e9f65aa96d686baadb36a030e7ec"

      def install
        bin.install "ghat"
      end
    end
  end

  test do
    system "#{bin}/ghat", "--help"
  end
end
