# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghat < Formula
  desc "Ghat is a tool for updating GHA dependencies"
  homepage "https://github.com/JamesWoolfenden/ghat#readme"
  version "0.0.15"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v0.0.15/ghat_0.0.15_darwin_arm64.tar.gz"
      sha256 "be83388acac8ac91a0c62ccf371d0d2c1840889d889ac976f6446b7b1c33b8fe"

      def install
        bin.install "ghat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v0.0.15/ghat_0.0.15_darwin_amd64.tar.gz"
      sha256 "887d7f6a447d7011de71da6681d2b050ebb24e37b05260893c0d6c9af96b56d6"

      def install
        bin.install "ghat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v0.0.15/ghat_0.0.15_linux_amd64.tar.gz"
      sha256 "1e5492403b08f04fdf596bc7971db6590eb27fc0b15416f8420238deb78bfbd1"

      def install
        bin.install "ghat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v0.0.15/ghat_0.0.15_linux_arm64.tar.gz"
      sha256 "216db81a8814b9a7f64b91cb0d45e48efe383e0934f665fc505fc360db8d574a"

      def install
        bin.install "ghat"
      end
    end
  end

  test do
    system "#{bin}/ghat", "--help"
  end
end
