# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitfab < Formula
  desc "Opens a git repo in a browser"
  homepage "https://github.com/JamesWoolfenden/gitfab#readme"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/gitfab/releases/download/v0.0.7/gitfab_0.0.7_darwin_amd64.tar.gz"
      sha256 "7b8c7e2180d3671163285fb3db2b515ecf9ac3c50d2e8f5753d7ff373598bcf2"

      define_method(:install) do
        bin.install "gitfab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JamesWoolfenden/gitfab/releases/download/v0.0.7/gitfab_0.0.7_darwin_arm64.tar.gz"
      sha256 "fb34f0cf49394fb79b914d327636514b9988f2a09ef6a0d6e85565d59509dfc6"

      define_method(:install) do
        bin.install "gitfab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/gitfab/releases/download/v0.0.7/gitfab_0.0.7_linux_amd64.tar.gz"
      sha256 "e85bd3bb95a1359988c59ea5eff94dad187b591e07239c523dfe2ea8b36e7310"
      define_method(:install) do
        bin.install "gitfab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/gitfab/releases/download/v0.0.7/gitfab_0.0.7_linux_arm64.tar.gz"
      sha256 "504f052472161a427e2624320815d73e08087c96d29f90f263614954ccc77482"
      define_method(:install) do
        bin.install "gitfab"
      end
    end
  end

  test do
    system "#{bin}/gitfab", "--help"
  end
end
