# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitfab < Formula
  desc "Opens a git repo in a browser"
  homepage "https://github.com/JamesWoolfenden/gitfab#readme"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/gitfab/releases/download/v0.0.5/gitfab_0.0.5_darwin_amd64.tar.gz"
      sha256 "ba82aa5cbb87f65e78244e2e375ddf0c1ee4dd49ec58d008d98ecc02ecd97b79"

      define_method(:install) do
        bin.install "gitfab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JamesWoolfenden/gitfab/releases/download/v0.0.5/gitfab_0.0.5_darwin_arm64.tar.gz"
      sha256 "13e0d29cba993de28dd42dfbeec54a08bb1fe504183cf90d17ae32c07cc8072c"

      define_method(:install) do
        bin.install "gitfab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/gitfab/releases/download/v0.0.5/gitfab_0.0.5_linux_amd64.tar.gz"
      sha256 "0a8bfc7e5de6b30622dd185cd88f9080cc732e978b10b114acea6e7228a39564"
      define_method(:install) do
        bin.install "gitfab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/gitfab/releases/download/v0.0.5/gitfab_0.0.5_linux_arm64.tar.gz"
      sha256 "d1381b103bbb204a560961eebf54bc45b80ca7a8c0f51a6024dab401ad4a78db"
      define_method(:install) do
        bin.install "gitfab"
      end
    end
  end

  test do
    system "#{bin}/gitfab", "--help"
  end
end
