# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pike < Formula
  desc "Pike is a tool for determining the permissions or policy required for IAC code"
  homepage "https://github.com/JamesWoolfenden/pike#readme"
  version "0.2.52"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/pike/releases/download/v0.2.52/pike_0.2.52_darwin_amd64.tar.gz"
      sha256 "f1ee35bda2cf8bcdadedeceaa589c172e2db57fc3fb3fd79c0a07a3c35834aa8"

      def install
        bin.install "pike"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JamesWoolfenden/pike/releases/download/v0.2.52/pike_0.2.52_darwin_arm64.tar.gz"
      sha256 "96154e167c53ed78bd8ff2c127c507348a80e5a5e930686ebb6eb3ef85aa8168"

      def install
        bin.install "pike"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/pike/releases/download/v0.2.52/pike_0.2.52_linux_amd64.tar.gz"
      sha256 "af844333563feca9889916aa9f46aabae7c644d6f8747da618776a5ce98b8093"

      def install
        bin.install "pike"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/pike/releases/download/v0.2.52/pike_0.2.52_linux_arm64.tar.gz"
      sha256 "e613fc42a83b11f0cf0d222e3816fa197da95b13825c8224c4491a460ce4e10e"

      def install
        bin.install "pike"
      end
    end
  end

  test do
    system "#{bin}/pike", "--help"
  end
end
