# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pike < Formula
  desc "Pike is a tool for determining the permissions or policy required for IAC code"
  homepage "https://github.com/JamesWoolfenden/pike#readme"
  version "0.3.15"

  on_macos do
    on_intel do
      url "https://github.com/JamesWoolfenden/pike/releases/download/v0.3.15/pike_0.3.15_darwin_amd64.tar.gz"
      sha256 "bf29e1892b0340caeab7a221f6f54b988f9cfbd31bbe1d1adbe1e7448b521a4f"

      def install
        bin.install "pike"
      end
    end
    on_arm do
      url "https://github.com/JamesWoolfenden/pike/releases/download/v0.3.15/pike_0.3.15_darwin_arm64.tar.gz"
      sha256 "cf843f050c5045b3f9798f048893474ce8b4976af61e0bb8c37a479663346f0a"

      def install
        bin.install "pike"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JamesWoolfenden/pike/releases/download/v0.3.15/pike_0.3.15_linux_amd64.tar.gz"
        sha256 "9fb727e9b101d789a0dce9a27350ae937ed16bef3db8908ace1d6caf6dca25b7"

        def install
          bin.install "pike"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JamesWoolfenden/pike/releases/download/v0.3.15/pike_0.3.15_linux_arm64.tar.gz"
        sha256 "043902372b8d798b48c6c1255c8447c0463777b6b5d84561119c89883f1ed076"

        def install
          bin.install "pike"
        end
      end
    end
  end

  test do
    system "#{bin}/pike", "--help"
  end
end
