# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stevedore < Formula
  desc "stevedore is a tool for managing Dockerfile labels"
  homepage "https://github.com/JamesWoolfenden/stevedore#readme"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v0.0.5/stevedore_0.0.5_darwin_amd64.tar.gz"
      sha256 "8c9af1bd6f1b9ee3b046cd4d6fd61258f4f7e1cfa5b1e3061b0d9a84e9f020b1"

      def install
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v0.0.5/stevedore_0.0.5_darwin_arm64.tar.gz"
      sha256 "3d138780ec7ca1b786450b844415b2854dd3dc095e235ca8e584c11b5dfbf1e2"

      def install
        bin.install "stevedore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v0.0.5/stevedore_0.0.5_linux_amd64.tar.gz"
      sha256 "751538bc1674ad7d1a8c15d1557896df8a13352b1e9b30af7474663ed3608cca"

      def install
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v0.0.5/stevedore_0.0.5_linux_arm64.tar.gz"
      sha256 "5e6de926b4f801bb0cf67193bc48a97ad246b2ba126e3549a36906c43a00cfd9"

      def install
        bin.install "stevedore"
      end
    end
  end

  test do
    system "#{bin}/stevedore", "--help"
  end
end
