# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stevedore < Formula
  desc "stevedore is a tool for managing Dockerfile labels"
  homepage "https://github.com/JamesWoolfenden/stevedore#readme"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v0.0.8/stevedore_0.0.8_darwin_arm64.tar.gz"
      sha256 "b2a9b0adda230f136d41ad2894b36202fa8720c452e13f15399afa365fdbc09c"

      def install
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v0.0.8/stevedore_0.0.8_darwin_amd64.tar.gz"
      sha256 "5c319f4ec900f9eaa01fd09e0dd303be8d1e4f92f64b22ddd67894fdd91ca11a"

      def install
        bin.install "stevedore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v0.0.8/stevedore_0.0.8_linux_amd64.tar.gz"
      sha256 "d36fb55c436bcac4133ae8e0a21d6d7bad02b56990ce7851739f0c12ac635537"

      def install
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v0.0.8/stevedore_0.0.8_linux_arm64.tar.gz"
      sha256 "1a6dc78cbd5df2a3a9a1bb03395893db436b220de69f3779fa3b40ebd7b46694"

      def install
        bin.install "stevedore"
      end
    end
  end

  test do
    system "#{bin}/stevedore", "--help"
  end
end
