# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghat" do
  version "0.1.38"

  on_macos do
    on_intel do
      sha256 "aa53ef3206108da43315b26a9c611b314f69a4190062437eac4052ca810e96fa"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff8ed31c2c4754a61592c3bd0529d573ba3c57d750394071c8798cc617106640"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18c18c86b7494cfebf6e643a27193747104402931e5b2758c8050ab8ab8d96ee"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eef6d4eb465d809cad33511919bbeb6ba49ab53e70b6c76a710def9947458b35"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghat"
  desc "Ghat is a tool for updating GHA dependencies"
  homepage "https://github.com/JamesWoolfenden/ghat#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghat"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghat"]
    end
  end

  # No zap stanza required

end
