# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghat" do
  version "0.1.43"

  on_macos do
    on_intel do
      sha256 "a90739f08fe8733fa599b8bbcb4f801efc39c52237f205837fd508faeb5f2137"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a041ede8758edefc030d62fd5ec6babfc0e3dc53f0ac0bae0dfe2d5dab20dd30"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2caab6e8aee956e120e87b463401e19fec1d3a1838bdc067a02357f37e1fe43"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d09a32c39fbd43c7b45e84c921f801141589888e717e54e54586eefb52631eae"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghat"
  desc "Ghat is a tool for updating GHA dependencies"
  homepage "https://github.com/JamesWoolfenden/ghat#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghat"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghat"]
    end
  end

  # No zap stanza required

end
