# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghat" do
  version "0.1.37"

  on_macos do
    on_intel do
      sha256 "b39510bf7107f897721ab894bb9dcb50ffe46e458587ec7ec5eaeddc89cdb65c"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5aa98592b20e36688ccea284aef70cf8e0ec548af3045efe292095fc4e5c45c3"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27d0735066c69422478cba8192ad9283597103fc0814c69aa0a581d30248ba6b"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e046d91ebeee58d4136d87561e08f56f791bcb79a99f92b8b05e75abea3a307b"
      url "https://github.com/JamesWoolfenden/ghat/releases/download/v#{version}/ghat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghat"
  desc "Ghat is a tool for updating GHA dependencies"
  homepage "https://github.com/JamesWoolfenden/ghat#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghat"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghat"]
    end
  end

  # No zap stanza required

end
