# This file was generated by GoReleaser. DO NOT EDIT.
cask "pike" do
  version "1.0.12"

  on_macos do
    on_intel do
      sha256 "8ef3fbec87cfae577b4e446da74b5cb08721ba5f966a92655bbbf841d5a6882d"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "abc83527222e897866678f98e1d8b2f95749ff4023a64d940cfa984a4fda30c8"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "16a3f5f26d52c453bf6230115077601430663fea7cec93517aa7ddf3dccd6c35"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "23e84a76a7adbf3d32a841692de97111fb9d97a5e244551dfdc3c3bdab734c2a"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pike"
  desc "Pike is a tool for determining the permissions or policy required for IAC code"
  homepage "https://github.com/JamesWoolfenden/pike#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pike"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pike"]
    end
  end

  # No zap stanza required

end
