# This file was generated by GoReleaser. DO NOT EDIT.
cask "pike" do
  version "0.4.7"

  on_macos do
    on_intel do
      sha256 "051187a2086a9b67514ae3846c6b8d711b7b3d05f94976dfe56e4c7fe68cc1e8"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3446f074af4f615e6f033be39a6faae9d24946d8ae68426a5da257e1ac081b7"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ea2808422deee9cb8bed41d5024f8db63e235a0bda1ca514035939e8608bf14"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "225eae9854011f2b18b4ee440ca6dab71a79c960c44b0940e1463b211ab36575"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pike"
  desc "Pike is a tool for determining the permissions or policy required for IAC code"
  homepage "https://github.com/JamesWoolfenden/pike#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pike"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pike"]
    end
  end

  # No zap stanza required

end
