# This file was generated by GoReleaser. DO NOT EDIT.
cask "pike" do
  version "0.4.6"

  on_macos do
    on_intel do
      sha256 "8c0b6c81e62663daf9569f72ab06030dce3e07d8cff2085c6c47215963a1dee3"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97f1282e19d1cfeadbe329c0ebac74ba03478d927488be846538c8be63b2d39d"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e31b1cbfe39135b788a1941c4235e75f53a63db995b072be076dd96bdefee637"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4592912d8a1c1acb0f2f3507f1b3b01637a1793dd020736d8f32fc9b4e01b5ab"
      url "https://github.com/JamesWoolfenden/pike/releases/download/v#{version}/pike_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pike"
  desc "Pike is a tool for determining the permissions or policy required for IAC code"
  homepage "https://github.com/JamesWoolfenden/pike#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pike"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pike"]
    end
  end

  # No zap stanza required

end
