# This file was generated by GoReleaser. DO NOT EDIT.
cask "sato" do
  version "0.1.50"

  on_macos do
    on_intel do
      sha256 "961376d2912097cb5f3a56d360c89eb04b976ec01518fde54415b4b4dfc260d0"
      url "https://github.com/JamesWoolfenden/sato/releases/download/v#{version}/sato_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3231e4631a93b71fd36b077bd864602402e49521f766eecbc459ad854c3e04c4"
      url "https://github.com/JamesWoolfenden/sato/releases/download/v#{version}/sato_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b98a13b7a187f68d51fb3a483db56be227af8beb379cbaf8d2e8a8bd215f89b"
      url "https://github.com/JamesWoolfenden/sato/releases/download/v#{version}/sato_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7527275c9ccfc742c8e6aee2630ae6162dc3686c012ac3a7dd9b227040dee45f"
      url "https://github.com/JamesWoolfenden/sato/releases/download/v#{version}/sato_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sato"
  desc "Sato is for converting Cloudformation to Terraform"
  homepage "https://github.com/JamesWoolfenden/sato#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sato"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sato"]
    end
  end

  # No zap stanza required

end
