# This file was generated by GoReleaser. DO NOT EDIT.
cask "stevedore" do
  name "stevedore"
  desc "stevedore is a tool for managing Dockerfile labels"
  homepage "https://github.com/JamesWoolfenden/stevedore#readme"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stevedore"

  on_macos do
    on_intel do
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_darwin_amd64.tar.gz"
      sha256 "b0891bc797bb6bc2779e78cb68c9103da45613890b86642faf2ec31e9f386ad5"
    end
    on_arm do
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_darwin_arm64.tar.gz"
      sha256 "3a4c9da5ef119a6703d1170edc2cec25a78c5784e894e43c293cd8ca84b75d11"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_linux_amd64.tar.gz"
      sha256 "9efada606dd45bc61c5a44fdd9a33a11cf07a61cf4f40eba5fb6f76bbde8ca83"
    end
    on_arm do
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_linux_arm64.tar.gz"
      sha256 "e240fb32ce1026c22788be6644891dc5375a573df85bf73aebfc5754336cac4e"
    end
  end

  # No zap stanza required
end
