# This file was generated by GoReleaser. DO NOT EDIT.
cask "stevedore" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "d0fd85173f6bf4ce3beb9c4df9cd3ae3a37bdd0ced6f86384613dea557f2d912"
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "16e9f22cdbe8d625a6c2ea025d59a23a959c3d79f64984ec24bc40ee14708e68"
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a51196cd7507531f1ec7917656c993cf73f513b9c5a70dfff5f82f8ef5c7ef45"
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "125736991dcd9faac0912b9206ed59665d685c90c4ecdf33a24e2e231a9cf493"
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stevedore"
  desc "stevedore is a tool for managing Dockerfile labels"
  homepage "https://github.com/JamesWoolfenden/stevedore#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stevedore"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stevedore"]
    end
  end

  # No zap stanza required

end
