# This file was generated by GoReleaser. DO NOT EDIT.
cask "stevedore" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "f03967b787b5d43070958f6dadfbb2fefdcbfca4bf345f3beec50a1d16f2c294"
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c9027da2f186f71dba716ce18880e51366266733bba1760f33250d25395874d"
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "74c320100507b9d811a9720c177af209ac7220ef103b944f244036ac2e2d21ac"
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "398eff85b39cca950ce07fa5b40a22afab14df4fd729e94730084052cc307acb"
      url "https://github.com/JamesWoolfenden/stevedore/releases/download/v#{version}/stevedore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stevedore"
  desc "stevedore is a tool for managing Dockerfile labels"
  homepage "https://github.com/JamesWoolfenden/stevedore#readme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stevedore"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stevedore"]
    end
  end

  # No zap stanza required

end
